@extends('layouts.app')

@section('title', 'Tambah Edukasi — Prevanta')

@section('content')
<x-portal-shell role="kader" active="education" class="max-w-5xl">
    <x-page-header eyebrow="Materi Baru" title="Tambah Edukasi" description="Buat materi singkat dan informatif untuk orang tua balita." />
    <form method="POST" action="{{ route('kader.education.store') }}" enctype="multipart/form-data" class="grid gap-5">@csrf<x-card><div class="grid gap-5"><x-form-field label="Judul Edukasi" name="judul" placeholder="Masukkan judul artikel" required /><label class="grid gap-2 text-sm font-semibold text-ink-700">Kategori<select name="kategori" required class="rounded-xl border border-prevanta-100 bg-[#fcfafb] px-4 py-3 font-normal"><option value="">Pilih kategori</option>@foreach (['Gizi','Tumbuh Kembang','Imunisasi','Pola Asuh'] as $category)<option value="{{ $category }}" @selected(old('kategori') === $category)>{{ $category }}</option>@endforeach</select>@error('kategori')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label><label class="grid gap-2 text-sm font-semibold text-ink-700">Gambar Sampul<span class="grid min-h-36 cursor-pointer place-items-center rounded-2xl border-2 border-dashed border-prevanta-200 bg-prevanta-50 text-center"><span><x-icon name="upload" class="mx-auto size-7 text-prevanta-600" /><span class="mt-2 block text-sm font-bold text-prevanta-700">Pilih gambar</span><span class="mt-1 block text-xs font-normal text-ink-500">PNG, JPG, atau WEBP, maksimal 2 MB</span></span><input type="file" name="gambar" accept="image/png,image/jpeg,image/webp" class="sr-only"></span>@error('gambar')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label><label class="grid gap-2 text-sm font-semibold text-ink-700">Isi Edukasi<textarea name="konten" rows="10" required placeholder="Tulis materi edukasi di sini..." class="rounded-xl border border-prevanta-100 bg-[#fcfafb] px-4 py-3 font-normal leading-6 outline-none">{{ old('konten') }}</textarea>@error('konten')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label></div></x-card><div class="flex justify-end gap-3"><a href="{{ route('kader.education') }}" class="rounded-xl border border-prevanta-200 px-5 py-3 text-sm font-bold text-prevanta-700">Batal</a><button type="submit" class="rounded-xl bg-prevanta-600 px-5 py-3 text-sm font-bold text-white">Publikasikan</button></div></form>
</x-portal-shell>
@endsection
