@extends('layouts.app')

@section('title', 'Tambah Edukasi — Prevanta')

@section('content')
<x-portal-shell role="kader" active="education" class="max-w-5xl">
    <x-page-header eyebrow="Materi Baru" title="Tambah Edukasi" description="Buat materi singkat dan informatif untuk orang tua balita." />
    <form class="grid gap-5" data-demo-form><x-card><div class="grid gap-5"><x-form-field label="Judul Edukasi" name="title" placeholder="Masukkan judul artikel" required /><label class="grid gap-2 text-sm font-semibold text-ink-700">Kategori<select class="rounded-xl border border-prevanta-100 bg-[#fcfafb] px-4 py-3 font-normal"><option>Gizi</option><option>Tumbuh Kembang</option><option>Imunisasi</option><option>Pola Asuh</option></select></label><label class="grid gap-2 text-sm font-semibold text-ink-700">Gambar Sampul<span class="grid min-h-36 cursor-pointer place-items-center rounded-2xl border-2 border-dashed border-prevanta-200 bg-prevanta-50 text-center"><span><x-icon name="upload" class="mx-auto size-7 text-prevanta-600" /><span class="mt-2 block text-sm font-bold text-prevanta-700">Pilih gambar</span><span class="mt-1 block text-xs font-normal text-ink-500">PNG atau JPG, maksimal 2 MB</span></span><input type="file" class="sr-only"></span></label><label class="grid gap-2 text-sm font-semibold text-ink-700">Ringkasan<textarea rows="3" placeholder="Ringkasan singkat artikel..." class="rounded-xl border border-prevanta-100 bg-[#fcfafb] px-4 py-3 font-normal outline-none"></textarea></label><label class="grid gap-2 text-sm font-semibold text-ink-700">Isi Edukasi<textarea rows="10" placeholder="Tulis materi edukasi di sini..." class="rounded-xl border border-prevanta-100 bg-[#fcfafb] px-4 py-3 font-normal leading-6 outline-none"></textarea></label></div></x-card><p class="hidden rounded-xl bg-mint-50 p-4 text-sm font-semibold text-mint-600" data-form-message>Artikel demo siap ditinjau. Tidak ada data yang disimpan.</p><div class="flex justify-end gap-3"><a href="{{ route('kader.education') }}" class="rounded-xl border border-prevanta-200 px-5 py-3 text-sm font-bold text-prevanta-700">Batal</a><button class="rounded-xl bg-prevanta-600 px-5 py-3 text-sm font-bold text-white">Publikasikan</button></div></form>
</x-portal-shell>
@endsection
