@extends('layouts.app')

@section('title', 'Profil Balita Kader — Prevanta')

@section('content')
<x-portal-shell role="kader" active="monitoring">
    @php($latest = $balita->pengukuran->last())
    <x-page-header eyebrow="Profil Balita" :title="$balita->nama" description="Data identitas dan riwayat pengukuran balita."><x-slot:actions><a href="{{ route('kader.measurement', $balita) }}" class="rounded-xl bg-prevanta-600 px-4 py-2.5 text-sm font-bold text-white">Input Pengukuran</a></x-slot:actions></x-page-header>
    <x-card><div class="flex flex-col gap-5 md:flex-row md:items-center"><div class="grid size-24 place-items-center rounded-full bg-prevanta-100 text-3xl font-bold text-prevanta-700">{{ mb_substr($balita->nama, 0, 1) }}</div><div class="flex-1"><div class="flex flex-wrap items-center gap-2"><h2 class="text-2xl font-bold">{{ $balita->nama }}</h2><x-status-pill :tone="$latest?->status_pertumbuhan === \App\GrowthStatus::Normal ? 'green' : 'amber'">{{ $latest?->status_pertumbuhan?->label() ?? 'Belum Diukur' }}</x-status-pill></div><p class="mt-2 text-sm text-ink-500">{{ $balita->jenis_kelamin->label() }} · {{ $balita->tanggal_lahir->diffForHumans(['parts' => 2]) }} · Anak dari {{ $balita->orangTua->user->name }}</p><p class="mt-1 text-xs text-ink-500">NIK {{ mb_substr($balita->nik, 0, 4) }}••••••{{ mb_substr($balita->nik, -4) }} · {{ $balita->alamat }}</p></div></div></x-card>
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><x-metric-tile label="Berat Badan" :value="$latest ? $latest->berat_badan.' kg' : '—'" :note="$latest?->status_pertumbuhan?->label() ?? 'Belum diukur'" icon="chart" /><x-metric-tile label="Panjang / Tinggi" :value="$latest ? $latest->tinggi_badan.' cm' : '—'" note="PB/U atau TB/U sesuai usia" icon="chart" tone="mint" /><x-metric-tile label="Z-score Otomatis" :value="$latest?->z_score !== null ? $latest->z_score.' SD' : '—'" note="Standar WHO" icon="clipboard" tone="blue" /><x-metric-tile label="Pengukuran" :value="$latest?->tanggal_pengukuran->translatedFormat('d M') ?? '—'" note="Terakhir diperbarui" icon="calendar" tone="sand" /></div>
    <div class="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><x-growth-chart title="Grafik KMS" :measurements="$balita->pengukuran" /><x-card><h2 class="font-bold">Data Orang Tua</h2><dl class="mt-5 grid gap-4 text-sm">@foreach ([['Nama',$balita->orangTua->user->name],['Nomor HP',$balita->orangTua->user->no_hp],['Hubungan',str($balita->orangTua->hubungan_dengan_balita)->headline()],['Alamat',$balita->alamat]] as [$label,$value])<div><dt class="text-xs text-ink-500">{{ $label }}</dt><dd class="mt-1 font-semibold">{{ $value }}</dd></div>@endforeach</dl></x-card></div>
</x-portal-shell>
@endsection
