@extends('layouts.app')

@section('title', 'Dashboard Kader — Prevanta')

@section('content')
<x-portal-shell role="kader" active="dashboard">
    <section class="relative overflow-hidden rounded-3xl bg-gradient-to-r from-prevanta-800 to-prevanta-500 p-7 text-white"><p class="text-sm font-semibold text-prevanta-100">Posyandu Mawar Melati · RW 03</p><h1 class="mt-2 text-3xl font-bold">Selamat Datang, {{ auth()->user()->name }}!</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-prevanta-100">Pantau kondisi balita, lengkapi data pengukuran, dan kelola kegiatan Posyandu hari ini.</p><span class="absolute -bottom-24 -right-10 size-72 rounded-full bg-white/10"></span></section>
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><x-metric-tile label="Total Balita" :value="$metrics['total']" note="Terdaftar di Posyandu" icon="users" /><x-metric-tile label="Sudah Diukur" :value="$metrics['measured']" note="Bulan ini" icon="clipboard" tone="mint" /><x-metric-tile label="Belum Diukur" :value="$metrics['unmeasured']" note="Perlu ditindaklanjuti" icon="history" tone="sand" /><x-metric-tile label="Pertumbuhan Normal" :value="$metrics['normal']" note="Pengukuran terbaru" icon="chart" tone="mint" /><x-metric-tile label="Perlu Dipantau" :value="$metrics['monitor']" note="Status waspada" icon="bell" tone="sand" /><x-metric-tile label="Risiko Stunting" :value="$metrics['risk']" note="Butuh rujukan bidan" icon="clipboard" tone="rose" /></div>
    <div class="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><x-growth-chart title="Tren Pengukuran Bulanan" subtitle="Jumlah balita yang diukur selama enam bulan" /><x-card><div class="flex items-center justify-between"><h2 class="font-bold">Kelompok Usia</h2><a href="{{ route('kader.monitoring') }}" class="text-xs font-bold text-prevanta-600">Lihat semua</a></div><div class="mt-5 grid gap-4">@foreach ([['0–6 bulan',12,18],['7–12 bulan',16,24],['1–2 tahun',19,28],['2–5 tahun',21,30]] as [$age,$count,$percent])<div><div class="flex justify-between text-sm"><span class="text-ink-500">{{ $age }}</span><b>{{ $count }} anak</b></div><div class="mt-2 h-2 rounded-full bg-prevanta-50"><div class="h-2 rounded-full bg-prevanta-500" style="width: {{ $percent }}%"></div></div></div>@endforeach</div></x-card></div>
</x-portal-shell>
@endsection
