@extends('layouts.app')

@section('title', 'Pengukuran Balita — Prevanta')

@section('content')
<x-portal-shell role="kader" active="monitoring" class="max-w-5xl">
    <x-page-header eyebrow="Pencatatan KMS" title="Pengukuran Balita" :description="'Masukkan hasil pengukuran '.$balita->nama.' pada kunjungan hari ini.'" />
    <x-card class="bg-prevanta-50"><div class="flex items-center gap-4"><div class="grid size-14 place-items-center rounded-full bg-white text-xl font-bold text-prevanta-700">{{ mb_substr($balita->nama, 0, 1) }}</div><div><h2 class="font-bold">{{ $balita->nama }}</h2><p class="mt-1 text-xs text-ink-500">{{ $balita->jenis_kelamin->label() }} · {{ $balita->tanggal_lahir->diffForHumans(['parts' => 2]) }} · Pengukuran terakhir {{ $balita->pengukuranTerbaru?->tanggal_pengukuran->translatedFormat('d M Y') ?? 'belum ada' }}</p></div></div></x-card>
    <form method="POST" action="{{ route('kader.measurements.store', $balita) }}" enctype="multipart/form-data" class="grid gap-5">@csrf<x-card><h2 class="font-bold">Hasil Pengukuran</h2><div class="mt-5 grid gap-4 sm:grid-cols-2"><x-form-field label="Tanggal Pengukuran" name="tanggal_pengukuran" type="date" required /><x-form-field label="Berat Badan (kg)" name="berat_badan" type="number" step="0.01" placeholder="11.8" required /><x-form-field label="Tinggi Badan (cm)" name="tinggi_badan" type="number" step="0.01" placeholder="86" required /><x-form-field label="Lingkar Kepala (cm)" name="lingkar_kepala" type="number" step="0.01" placeholder="47" /><x-form-field label="Lingkar Lengan Atas (cm)" name="lingkar_lengan_atas" type="number" step="0.01" placeholder="14.5" /><x-form-field label="Z-score" name="z_score" type="number" step="0.01" placeholder="-0.3" /><label class="grid gap-2 text-sm font-semibold text-ink-700">Status Pertumbuhan<select name="status_pertumbuhan" required class="rounded-xl border border-prevanta-100 bg-[#fcfafb] px-4 py-3 font-normal"><option value="">Pilih status</option>@foreach (\App\GrowthStatus::cases() as $status)<option value="{{ $status->value }}" @selected(old('status_pertumbuhan') === $status->value)>{{ $status->label() }}</option>@endforeach</select>@error('status_pertumbuhan')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label><label class="grid gap-2 text-sm font-semibold text-ink-700">Foto Pengukuran<input type="file" name="foto" accept="image/png,image/jpeg,image/webp" class="rounded-xl border border-prevanta-100 bg-[#fcfafb] px-4 py-3 font-normal">@error('foto')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label></div></x-card><div class="flex justify-end gap-3"><a href="{{ route('kader.child-profile', $balita) }}" class="rounded-xl border border-prevanta-200 px-5 py-3 text-sm font-bold text-prevanta-700">Batal</a><button type="submit" class="rounded-xl bg-prevanta-600 px-5 py-3 text-sm font-bold text-white">Simpan Pengukuran</button></div></form>
</x-portal-shell>
@endsection
