@extends('layouts.app')

@section('title', 'Pengukuran Balita — Prevanta')

@section('content')
<x-portal-shell role="kader" active="monitoring" class="max-w-5xl">
    <x-page-header eyebrow="Pencatatan KMS" title="Pengukuran Balita" description="Masukkan hasil pengukuran Arka Pratama pada kunjungan hari ini." />
    <x-card class="bg-prevanta-50"><div class="flex items-center gap-4"><div class="grid size-14 place-items-center rounded-full bg-white text-xl font-bold text-prevanta-700">A</div><div><h2 class="font-bold">Arka Pratama</h2><p class="mt-1 text-xs text-ink-500">Laki-laki · 2 tahun 4 bulan · Pengukuran terakhir 12 Sep 2026</p></div></div></x-card>
    <form class="grid gap-5" data-demo-form><x-card><h2 class="font-bold">Hasil Pengukuran</h2><div class="mt-5 grid gap-4 sm:grid-cols-2"><x-form-field label="Tanggal Pengukuran" name="date" type="date" required /><x-form-field label="Berat Badan (kg)" name="weight" type="number" placeholder="11.8" required /><x-form-field label="Tinggi Badan (cm)" name="height" type="number" placeholder="86" required /><x-form-field label="Lingkar Kepala (cm)" name="head" type="number" placeholder="47" /><x-form-field label="Lingkar Lengan (cm)" name="arm" type="number" placeholder="14.5" /><label class="grid gap-2 text-sm font-semibold text-ink-700">Cara Ukur<select class="rounded-xl border border-prevanta-100 bg-[#fcfafb] px-4 py-3 font-normal"><option>Berdiri</option><option>Terlentang</option></select></label></div><label class="mt-4 grid gap-2 text-sm font-semibold text-ink-700">Catatan<textarea rows="4" placeholder="Catatan kondisi anak..." class="rounded-xl border border-prevanta-100 bg-[#fcfafb] px-4 py-3 font-normal outline-none focus:border-prevanta-400"></textarea></label></x-card><p class="hidden rounded-xl bg-mint-50 p-4 text-sm font-semibold text-mint-600" data-form-message>Pengukuran demo berhasil divalidasi. Belum dikirim ke backend.</p><div class="flex justify-end gap-3"><a href="{{ route('kader.child-profile') }}" class="rounded-xl border border-prevanta-200 px-5 py-3 text-sm font-bold text-prevanta-700">Batal</a><button class="rounded-xl bg-prevanta-600 px-5 py-3 text-sm font-bold text-white">Simpan Pengukuran</button></div></form>
</x-portal-shell>
@endsection
