@extends('layouts.app')

@section('title', 'Riwayat dan History — Prevanta')

@section('content')
<x-portal-shell role="bidan" active="history">
    <x-page-header eyebrow="Data Pengukuran" title="Riwayat dan History" description="Riwayat verifikasi dan perkembangan balita di seluruh Posyandu binaan." />
    <x-card padding="p-4"><div class="flex flex-col gap-3 md:flex-row"><label class="relative flex-1"><x-icon name="search" class="absolute left-3 top-3 size-5 text-ink-500" /><input type="search" placeholder="Cari nama balita, orang tua, atau Posyandu..." class="w-full rounded-xl border border-prevanta-100 py-2.5 pl-11 pr-4 text-sm outline-none"></label><select class="rounded-xl border border-prevanta-100 bg-white px-4 text-sm"><option>Semua Posyandu</option><option>Mawar Melati</option><option>Anggrek</option></select><select class="rounded-xl border border-prevanta-100 bg-white px-4 text-sm"><option>Semua Status</option><option>Terverifikasi</option><option>Perlu Tindak Lanjut</option></select></div></x-card>
    <div class="grid gap-4">@foreach ([['Arka Pratama','2 tahun 4 bulan','11,8 kg','86 cm','Normal','Mawar Melati'],['Aisyah Putri','10 bulan','7,1 kg','67 cm','Perlu Dipantau','Mawar Melati'],['Raka Saputra','1 tahun 7 bulan','9,2 kg','76 cm','Normal','Anggrek'],['Nabila Zahra','3 tahun 1 bulan','11,1 kg','86 cm','Risiko Stunting','Kenanga']] as [$name,$age,$weight,$height,$status,$post])<x-card padding="p-4 sm:p-5"><div class="flex flex-col gap-4 lg:flex-row lg:items-center"><div class="flex min-w-0 flex-1 items-center gap-4"><div class="grid size-14 shrink-0 place-items-center rounded-full bg-prevanta-100 text-lg font-bold text-prevanta-700">{{ mb_substr($name,0,1) }}</div><div><div class="flex flex-wrap items-center gap-2"><h2 class="font-bold">{{ $name }}</h2><x-status-pill :tone="$status === 'Normal' ? 'green' : 'rose'">{{ $status }}</x-status-pill></div><p class="mt-1 text-xs text-ink-500">{{ $age }} · Posyandu {{ $post }} · 12 Sep 2026</p></div></div><div class="flex gap-6 text-sm"><span><b class="block">{{ $weight }}</b><small class="text-ink-500">Berat</small></span><span><b class="block">{{ $height }}</b><small class="text-ink-500">Tinggi</small></span></div><a href="{{ route('bidan.verification') }}" class="rounded-xl bg-prevanta-600 px-4 py-2.5 text-center text-sm font-bold text-white">Periksa + Tindak</a></div></x-card>@endforeach</div>
</x-portal-shell>
@endsection
