@extends('layouts.app')

@section('title', 'Verifikasi Balita — Prevanta')

@section('content')
<x-portal-shell role="bidan" active="verification">
    <x-page-header eyebrow="Antrean Verifikasi" title="Verifikasi Balita" description="Periksa hasil pengukuran dan tentukan tindak lanjut untuk Aisyah Putri."><x-slot:actions><a href="{{ route('bidan.history') }}" class="rounded-xl border border-prevanta-200 bg-white px-4 py-2.5 text-sm font-bold text-prevanta-700">← Kembali</a></x-slot:actions></x-page-header>
    <x-card class="bg-gradient-to-r from-white to-prevanta-50"><div class="flex flex-col gap-5 sm:flex-row sm:items-center"><div class="grid size-20 place-items-center rounded-full bg-prevanta-100 text-2xl font-bold text-prevanta-700">A</div><div class="flex-1"><div class="flex flex-wrap items-center gap-2"><h2 class="text-xl font-bold">Aisyah Putri</h2><x-status-pill tone="rose">Perlu Dipantau</x-status-pill></div><p class="mt-2 text-sm text-ink-500">Perempuan · 10 bulan · Ibu Siti Rahayu</p><p class="mt-1 text-xs text-ink-500">Diukur Kader Siti · 12 September 2026 · Posyandu Mawar Melati</p></div></div></x-card>
    <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><x-metric-tile label="Berat Badan" value="7,1 kg" note="Di bawah median" icon="chart" tone="rose" /><x-metric-tile label="Panjang Badan" value="67 cm" note="Perlu dipantau" icon="chart" tone="sand" /><x-metric-tile label="Lingkar Kepala" value="43 cm" note="Rentang normal" icon="users" tone="mint" /><x-metric-tile label="BB/PB" value="-1,8 SD" note="Mendekati batas" icon="clipboard" tone="rose" /></div>
    <div class="grid gap-5 xl:grid-cols-[1.25fr_1fr]"><x-growth-chart title="Grafik Pertumbuhan Aisyah" subtitle="Kurva berat dan panjang badan menurut usia" /><form class="grid gap-4" data-demo-form><x-card><h2 class="font-bold">Hasil Pemeriksaan Bidan</h2><div class="mt-5 grid gap-4"><label class="grid gap-2 text-sm font-semibold text-ink-700">Status Verifikasi<select class="rounded-xl border border-prevanta-100 bg-[#fcfafb] px-4 py-3 font-normal"><option>Data valid</option><option>Perlu pengukuran ulang</option></select></label><label class="grid gap-2 text-sm font-semibold text-ink-700">Kesimpulan<select class="rounded-xl border border-prevanta-100 bg-[#fcfafb] px-4 py-3 font-normal"><option>Perlu dipantau</option><option>Normal</option><option>Risiko stunting</option></select></label><label class="grid gap-2 text-sm font-semibold text-ink-700">Rekomendasi<textarea rows="5" class="rounded-xl border border-prevanta-100 bg-[#fcfafb] px-4 py-3 font-normal outline-none" placeholder="Tuliskan rekomendasi tindak lanjut..."></textarea></label><label class="flex items-center gap-3 text-sm text-ink-700"><input type="checkbox" class="size-4 accent-prevanta-600"> Jadwalkan kunjungan ulang</label><button class="rounded-xl bg-prevanta-600 px-5 py-3 text-sm font-bold text-white">Verifikasi & Simpan</button><p class="hidden rounded-xl bg-mint-50 p-3 text-xs font-semibold text-mint-600" data-form-message>Verifikasi demo selesai. Data belum disimpan.</p></div></x-card></form></div>
</x-portal-shell>
@endsection
